{
  "openapi" : "3.0.0",
  "info" : {
    "description" : "CHPQA Schemes and Submissions Proxy/Facade API",
    "title" : "CHPQA Alpha Prototype API",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "/"
  } ],
  "security" : [ {
    "ApiKey" : [ ]
  } ],
  "paths" : {
    "/schemes/{userId}" : {
      "get" : {
        "parameters" : [ {
          "description" : "The user id of the Responsible Person (RP)",
          "explode" : false,
          "in" : "path",
          "name" : "userId",
          "required" : true,
          "schema" : {
            "$ref" : "#/components/schemas/UserId"
          },
          "style" : "simple"
        } ],
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/scheme"
                }
              }
            },
            "description" : "The Schemes available to the supplied userId"
          }
        },
        "summary" : "Read all schemes for the supplied userId"
      }
    },
    "/scheme/{ref}" : {
      "get" : {
        "parameters" : [ {
          "description" : "The identifier of the scheme",
          "explode" : false,
          "in" : "path",
          "name" : "ref",
          "required" : true,
          "schema" : {
            "$ref" : "#/components/schemas/schemeId"
          },
          "style" : "simple"
        } ],
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/scheme"
                }
              }
            },
            "description" : "The Scheme identified by the supplied ref parameter"
          },
          "404" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error"
                }
              }
            },
            "description" : "No Scheme found for the provided `ref`"
          },
          "500" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error"
                }
              }
            },
            "description" : "Unexpected error"
          }
        },
        "summary" : "Read a Scheme"
      }
    },
    "/submission/{ref}" : {
      "post" : {
        "parameters" : [ {
          "description" : "The Scheme ref",
          "explode" : false,
          "in" : "path",
          "name" : "ref",
          "required" : true,
          "schema" : {
            "$ref" : "#/components/schemas/schemeId"
          },
          "style" : "simple"
        } ],
        "responses" : {
          "201" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/scheme"
                }
              }
            },
            "description" : "The Scheme identified by the provided `ref`"
          },
          "404" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error"
                }
              }
            },
            "description" : "No Scheme found for the provided `ref` parameter"
          },
          "500" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error"
                }
              }
            },
            "description" : "Unexpected error"
          }
        },
        "summary" : "Create a submission"
      }
    }
  },
  "components" : {
    "schemas" : {
      "UserId" : {
        "description" : "The identifier for a Responsible Person (RP)",
        "type" : "string"
      },
      "schemeId" : {
        "description" : "The identifier of a schema",
        "type" : "string"
      },
      "scheme" : {
        "example" : {
          "boilers" : [ {
            "tagNumber" : 1.4658129805029452,
            "yearCommissioned" : 5.962133916683182,
            "maximumRatedPower" : "maximumRatedPower",
            "details" : "details",
            "model" : "model",
            "maximumRatedHeat" : "maximumRatedHeat",
            "type" : "type",
            "manufacturer" : "manufacturer"
          }, {
            "tagNumber" : 1.4658129805029452,
            "yearCommissioned" : 5.962133916683182,
            "maximumRatedPower" : "maximumRatedPower",
            "details" : "details",
            "model" : "model",
            "maximumRatedHeat" : "maximumRatedHeat",
            "type" : "type",
            "manufacturer" : "manufacturer"
          } ],
          "additionalInformation" : {
            "details" : "details"
          },
          "primeMovers" : [ {
            "tagNumber" : 0.8008281904610115,
            "yearCommissioned" : 6.027456183070403,
            "fuel" : "fuel",
            "maximumRatedPower" : "maximumRatedPower",
            "model" : "model",
            "maximumRatedHeat" : "maximumRatedHeat",
            "type" : "type",
            "manufacturer" : "manufacturer"
          }, {
            "tagNumber" : 0.8008281904610115,
            "yearCommissioned" : 6.027456183070403,
            "fuel" : "fuel",
            "maximumRatedPower" : "maximumRatedPower",
            "model" : "model",
            "maximumRatedHeat" : "maximumRatedHeat",
            "type" : "type",
            "manufacturer" : "manufacturer"
          } ],
          "details" : {
            "fuelBillFrequency" : "Monthly",
            "diagrams" : [ "diagrams", "diagrams" ],
            "sector" : "Chemical industry"
          },
          "info" : {
            "ref" : "ref",
            "name" : "name"
          },
          "meters" : {
            "electricityMeters" : [ {
              "yearInstalled" : 5.637376656633329,
              "serialNumber" : "serialNumber",
              "outputsRange" : "outputsRange",
              "reading" : null,
              "tag" : "tag",
              "modelType" : "modelType",
              "uncertainty" : 2.3021358869347655,
              "diagramReferenceNumber" : "diagramReferenceNumber",
              "meterPointReference" : "meterPointReference",
              "outputsUnit" : "outputsUnit"
            }, {
              "yearInstalled" : 5.637376656633329,
              "serialNumber" : "serialNumber",
              "outputsRange" : "outputsRange",
              "reading" : null,
              "tag" : "tag",
              "modelType" : "modelType",
              "uncertainty" : 2.3021358869347655,
              "diagramReferenceNumber" : "diagramReferenceNumber",
              "meterPointReference" : "meterPointReference",
              "outputsUnit" : "outputsUnit"
            } ],
            "fuelMeters" : [ {
              "yearInstalled" : 5.637376656633329,
              "serialNumber" : "serialNumber",
              "outputsRange" : "outputsRange",
              "reading" : null,
              "tag" : "tag",
              "modelType" : "modelType",
              "uncertainty" : 2.3021358869347655,
              "diagramReferenceNumber" : "diagramReferenceNumber",
              "meterPointReference" : "meterPointReference",
              "outputsUnit" : "outputsUnit"
            }, {
              "yearInstalled" : 5.637376656633329,
              "serialNumber" : "serialNumber",
              "outputsRange" : "outputsRange",
              "reading" : null,
              "tag" : "tag",
              "modelType" : "modelType",
              "uncertainty" : 2.3021358869347655,
              "diagramReferenceNumber" : "diagramReferenceNumber",
              "meterPointReference" : "meterPointReference",
              "outputsUnit" : "outputsUnit"
            } ],
            "heatMeters" : [ {
              "yearInstalled" : 5.637376656633329,
              "serialNumber" : "serialNumber",
              "outputsRange" : "outputsRange",
              "reading" : null,
              "tag" : "tag",
              "modelType" : "modelType",
              "uncertainty" : 2.3021358869347655,
              "diagramReferenceNumber" : "diagramReferenceNumber",
              "meterPointReference" : "meterPointReference",
              "outputsUnit" : "outputsUnit"
            }, {
              "yearInstalled" : 5.637376656633329,
              "serialNumber" : "serialNumber",
              "outputsRange" : "outputsRange",
              "reading" : null,
              "tag" : "tag",
              "modelType" : "modelType",
              "uncertainty" : 2.3021358869347655,
              "diagramReferenceNumber" : "diagramReferenceNumber",
              "meterPointReference" : "meterPointReference",
              "outputsUnit" : "outputsUnit"
            } ]
          }
        },
        "properties" : {
          "info" : {
            "$ref" : "#/components/schemas/scheme_info"
          },
          "details" : {
            "$ref" : "#/components/schemas/details"
          },
          "primeMovers" : {
            "items" : {
              "$ref" : "#/components/schemas/primeMover"
            },
            "type" : "array"
          },
          "boilers" : {
            "items" : {
              "$ref" : "#/components/schemas/boiler"
            },
            "type" : "array"
          },
          "additionalInformation" : {
            "$ref" : "#/components/schemas/scheme_additionalInformation"
          },
          "meters" : {
            "$ref" : "#/components/schemas/meters"
          }
        },
        "required" : [ "boilers", "details", "info", "meters", "primeMovers" ],
        "type" : "object"
      },
      "details" : {
        "example" : {
          "fuelBillFrequency" : "Monthly",
          "diagrams" : [ "diagrams", "diagrams" ],
          "sector" : "Chemical industry"
        },
        "properties" : {
          "sector" : {
            "enum" : [ "Chemical industry", "Commerce", "Construction", "Electrical and instrument engineering", "Extraction, mining and agglomeration", "Food, beverages and tobacco", "Iron and steel", "Mechanical engineering and metal products", "Mineral products (eg glass, cement, bricks)", "Non ferrous metals", "Oil refineries", "Other", "Other industrial branches", "Paper, publishing and printing", "Power generation", "Public Administration", "Sewage treatment", "Textiles, clothing and footwear", "Transport", "Vehicles" ],
            "type" : "string"
          },
          "fuelBillFrequency" : {
            "enum" : [ "Monthly", "Quarterly", "Annually", "Other" ],
            "type" : "string"
          },
          "diagrams" : {
            "items" : {
              "type" : "string"
            },
            "type" : "array"
          }
        },
        "required" : [ "diagrams", "fuelBillFrequency", "sector" ],
        "type" : "object"
      },
      "primeMover" : {
        "example" : {
          "tagNumber" : 0.8008281904610115,
          "yearCommissioned" : 6.027456183070403,
          "fuel" : "fuel",
          "maximumRatedPower" : "maximumRatedPower",
          "model" : "model",
          "maximumRatedHeat" : "maximumRatedHeat",
          "type" : "type",
          "manufacturer" : "manufacturer"
        },
        "properties" : {
          "tagNumber" : {
            "type" : "number"
          },
          "type" : {
            "type" : "string"
          },
          "fuel" : {
            "type" : "string"
          },
          "manufacturer" : {
            "type" : "string"
          },
          "model" : {
            "type" : "string"
          },
          "yearCommissioned" : {
            "type" : "number"
          },
          "maximumRatedHeat" : {
            "type" : "string"
          },
          "maximumRatedPower" : {
            "type" : "string"
          }
        },
        "required" : [ "fuel", "manufacturer", "maximumRatedHeat", "maximumRatedPower", "model", "tagNumber", "type", "yearCommissioned" ],
        "type" : "object"
      },
      "boiler" : {
        "example" : {
          "tagNumber" : 1.4658129805029452,
          "yearCommissioned" : 5.962133916683182,
          "maximumRatedPower" : "maximumRatedPower",
          "details" : "details",
          "model" : "model",
          "maximumRatedHeat" : "maximumRatedHeat",
          "type" : "type",
          "manufacturer" : "manufacturer"
        },
        "properties" : {
          "tagNumber" : {
            "type" : "number"
          },
          "type" : {
            "type" : "string"
          },
          "details" : {
            "type" : "string"
          },
          "manufacturer" : {
            "type" : "string"
          },
          "model" : {
            "type" : "string"
          },
          "yearCommissioned" : {
            "type" : "number"
          },
          "maximumRatedHeat" : {
            "type" : "string"
          },
          "maximumRatedPower" : {
            "type" : "string"
          }
        },
        "required" : [ "details", "manufacturer", "maximumRatedHeat", "maximumRatedPower", "model", "tagNumber", "type", "yearCommissioned" ],
        "type" : "object"
      },
      "meter" : {
        "example" : {
          "yearInstalled" : 5.637376656633329,
          "serialNumber" : "serialNumber",
          "outputsRange" : "outputsRange",
          "reading" : null,
          "tag" : "tag",
          "modelType" : "modelType",
          "uncertainty" : 2.3021358869347655,
          "diagramReferenceNumber" : "diagramReferenceNumber",
          "meterPointReference" : "meterPointReference",
          "outputsUnit" : "outputsUnit"
        },
        "properties" : {
          "tag" : {
            "type" : "string"
          },
          "diagramReferenceNumber" : {
            "type" : "string"
          },
          "yearInstalled" : {
            "type" : "number"
          },
          "outputsRange" : {
            "type" : "string"
          },
          "outputsUnit" : {
            "type" : "string"
          },
          "modelType" : {
            "type" : "string"
          },
          "uncertainty" : {
            "type" : "number"
          },
          "meterPointReference" : {
            "type" : "string"
          },
          "serialNumber" : {
            "type" : "string"
          },
          "reading" : {
            "$ref" : "#/components/schemas/meter_reading"
          }
        },
        "required" : [ "diagramReferenceNumber", "modelType", "outputsRange", "outputsUnit", "serialNumber", "tag", "uncertainty", "yearInstalled" ],
        "type" : "object"
      },
      "meters" : {
        "example" : {
          "electricityMeters" : [ {
            "yearInstalled" : 5.637376656633329,
            "serialNumber" : "serialNumber",
            "outputsRange" : "outputsRange",
            "reading" : null,
            "tag" : "tag",
            "modelType" : "modelType",
            "uncertainty" : 2.3021358869347655,
            "diagramReferenceNumber" : "diagramReferenceNumber",
            "meterPointReference" : "meterPointReference",
            "outputsUnit" : "outputsUnit"
          }, {
            "yearInstalled" : 5.637376656633329,
            "serialNumber" : "serialNumber",
            "outputsRange" : "outputsRange",
            "reading" : null,
            "tag" : "tag",
            "modelType" : "modelType",
            "uncertainty" : 2.3021358869347655,
            "diagramReferenceNumber" : "diagramReferenceNumber",
            "meterPointReference" : "meterPointReference",
            "outputsUnit" : "outputsUnit"
          } ],
          "fuelMeters" : [ {
            "yearInstalled" : 5.637376656633329,
            "serialNumber" : "serialNumber",
            "outputsRange" : "outputsRange",
            "reading" : null,
            "tag" : "tag",
            "modelType" : "modelType",
            "uncertainty" : 2.3021358869347655,
            "diagramReferenceNumber" : "diagramReferenceNumber",
            "meterPointReference" : "meterPointReference",
            "outputsUnit" : "outputsUnit"
          }, {
            "yearInstalled" : 5.637376656633329,
            "serialNumber" : "serialNumber",
            "outputsRange" : "outputsRange",
            "reading" : null,
            "tag" : "tag",
            "modelType" : "modelType",
            "uncertainty" : 2.3021358869347655,
            "diagramReferenceNumber" : "diagramReferenceNumber",
            "meterPointReference" : "meterPointReference",
            "outputsUnit" : "outputsUnit"
          } ],
          "heatMeters" : [ {
            "yearInstalled" : 5.637376656633329,
            "serialNumber" : "serialNumber",
            "outputsRange" : "outputsRange",
            "reading" : null,
            "tag" : "tag",
            "modelType" : "modelType",
            "uncertainty" : 2.3021358869347655,
            "diagramReferenceNumber" : "diagramReferenceNumber",
            "meterPointReference" : "meterPointReference",
            "outputsUnit" : "outputsUnit"
          }, {
            "yearInstalled" : 5.637376656633329,
            "serialNumber" : "serialNumber",
            "outputsRange" : "outputsRange",
            "reading" : null,
            "tag" : "tag",
            "modelType" : "modelType",
            "uncertainty" : 2.3021358869347655,
            "diagramReferenceNumber" : "diagramReferenceNumber",
            "meterPointReference" : "meterPointReference",
            "outputsUnit" : "outputsUnit"
          } ]
        },
        "properties" : {
          "fuelMeters" : {
            "items" : {
              "$ref" : "#/components/schemas/meter"
            },
            "type" : "array"
          },
          "electricityMeters" : {
            "items" : {
              "$ref" : "#/components/schemas/meter"
            },
            "type" : "array"
          },
          "heatMeters" : {
            "items" : {
              "$ref" : "#/components/schemas/meter"
            },
            "type" : "array"
          }
        },
        "required" : [ "electricityMeters", "fuelMeters", "heatMeters" ],
        "type" : "object"
      },
      "fuelMeterReading" : {
        "properties" : {
          "fuelCategory" : {
            "type" : "string"
          },
          "fuelType" : {
            "type" : "string"
          },
          "haveUsedCalculations" : {
            "type" : "boolean"
          },
          "values" : {
            "items" : {
              "$ref" : "#/components/schemas/meterReading"
            },
            "type" : "array"
          }
        },
        "type" : "object"
      },
      "heatMeterReading" : {
        "properties" : {
          "heatType" : {
            "type" : "string"
          },
          "haveUsedCalculations" : {
            "type" : "boolean"
          },
          "values" : {
            "items" : {
              "$ref" : "#/components/schemas/meterReading"
            },
            "type" : "array"
          }
        },
        "type" : "object"
      },
      "electricityMeterReading" : {
        "properties" : {
          "powerOutputType" : {
            "type" : "string"
          },
          "haveUsedCalculations" : {
            "type" : "boolean"
          },
          "values" : {
            "items" : {
              "$ref" : "#/components/schemas/meterReading"
            },
            "type" : "array"
          }
        },
        "type" : "object"
      },
      "meterReading" : {
        "properties" : {
          "month" : {
            "type" : "number"
          },
          "value" : {
            "type" : "number"
          }
        },
        "type" : "object"
      },
      "Error" : {
        "properties" : {
          "message" : {
            "description" : "A human readable error message",
            "type" : "string"
          }
        },
        "required" : [ "message" ],
        "type" : "object"
      },
      "scheme_info" : {
        "example" : {
          "ref" : "ref",
          "name" : "name"
        },
        "properties" : {
          "ref" : {
            "type" : "string"
          },
          "name" : {
            "type" : "string"
          }
        },
        "type" : "object"
      },
      "scheme_additionalInformation" : {
        "example" : {
          "details" : "details"
        },
        "properties" : {
          "details" : {
            "type" : "string"
          }
        },
        "type" : "object"
      },
      "meter_reading" : {
        "anyOf" : [ {
          "$ref" : "#/components/schemas/fuelMeterReading"
        }, {
          "$ref" : "#/components/schemas/heatMeterReading"
        }, {
          "$ref" : "#/components/schemas/electricityMeterReading"
        } ]
      }
    },
    "securitySchemes" : {
      "ApiKey" : {
        "in" : "header",
        "name" : "X-Api-Key",
        "type" : "apiKey"
      }
    }
  }
}
